### ISSUE TITLE
Search and Framework Download APIs

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/CompetencyFrameworks#11]
@siuc-nate is going to review the repository API document and we will work together to get a clear interface between Workit and CASS developed.

**Comment by siuc-nate** [comment]
For reference: http://docs.cassproject.org/index.html?doc=1-dqFFUHV0sec4GzD9noX4Qi09xNBUiFVveS4-dAsnPE

**Comment by siuc-nate** [comment]
@Lomilar The size and start parameters seem to be being ignored (or I am sending them incorrectly):

https://sandbox.service.cassproject.org/sky/repo/search?q=(@type:"http://schema.eduworks.com/cass/0.1/competency")&size=2&start=3 
returns the same data regardless of which size or start values are sent.

**Comment by siuc-nate** [comment]
@Lomilar Also, is there a parameter I can send to get a framework back as a hierarchical structure (or as a graph that can be assembled into one), rather than needing to make a GET request for every node and relation individually and assembling them?

Short of that, is there a way to include the data for the nodes and relations in the returned data for the framework, instead of just the URIs for them?

**Comment by Lomilar** [comment]
For URL parameters start and size, go ahead and work against dev.cassproject.org -- those parameters were not available in the 0.2 release. Dev has more of that functionality implemented.

https://dev.cassproject.org/api/custom/sky/repo/search?q=(@type:%22Competency%22)&size=2&start=5

As for the latter, there isn't at the moment. Because a framework could link to myriad records from servers across the globe, it didn't make sense to burden the server with aggregating those records.

Though to create the appropriate ASN framework in the ASN adapter, we will be doing exactly that.

That being said, there is an undocumented 'multiGet' call that will retrieve a number of records from a server _iff_ they reside on that server. This is used to pre-cache data. It's unadvised to do this if you are relying on the results to include all the records.

http://cassproject.github.io/CASS/files/src_main_js_cass_ebac.repository.js.html#l728

**Comment by siuc-nate** [comment]
Thanks.

It's probably not a big deal to do all of the HTTP GETs since CASS and Workit will be on the same server, but I was hoping to save some looping.  Not a huge hurdle, though.

Anyway, one more thing - the query seems to return the elasticsearch result set directly, meaning there's no information about the total number of results/pages, status/error messages, etc.  Is there a way to get that data? I think it's one or two layers up in the JSON elasticsearch normally sends back.

**Comment by Lomilar** [comment]
Results/pages, not yet. I can see if I can return those as headers. The status/error messages come back as HTTP error codes (or as no results). For a bad search phrase, unfortunately, the response ends up being an empty object ({}) instead of an empty array ([]) -- that's a bug.

cassproject/CASS#19
cassproject/CASS#20

**Comment by siuc-nate** [comment]
@Lomilar 
There seems to be a mismatch between the IDs in the framework's competency list and the IDs for the competencies themselves.  For example:
https://dev.cassproject.org/api/custom/data/schema.cassproject.org.0.2.Framework/76ffff33-bd15-4bf3-a007-4ce247d2216d/1495040497868
This framework's competency list starts with
https://dev.cassproject.org/api/custom/data/schema.cassproject.org.0.2.Competency/onet:1
which resolves fine, but the ID in that record is
https://dev.cassproject.org/api/custom/data/schema.cassproject.org.0.2.Competency/onet:1/1495040339831
which also resolves to the same record.

An identical problem exists within the relations' "source" and "target" properties:
https://dev.cassproject.org/api/custom/data/schema.cassproject.org.0.2.Relation/d0476c4a-964c-4c5a-a4cc-54a5880816b0
Again, they point to the shorter version of the ID that does not match the `@id` field of the competency.

IMO the ID in the framework's competency list and the source/target properties of the relation objects should exactly match the `@id` of the competency that is resolved. This would allow me to retrieve all of the competencies and all of the relations (in bulk), and connect them by comparing the source and target properties of the relations against the `@id`s of the competencies. 

I can do so by stripping off the last part of the competencies' `@ids` (including the last slash), but this seems fragile.

**Comment by Lomilar** [comment]
The last part of the ID is the version number/last updated timestamp. Because these things can change and be updated, there are some times when the competency needs to be specified in an immutable fashion (for instance, when someone claims you demonstrated some competency), and some times the latest version is desired (for instance, most of the time when included in a framework).

Including the version segment in the URL gets you an immutable version of the competency, and omitting it gets you the latest version of the competency. The version number will always be a number, and the id portion is a string identifier (and is typically, but not always a UUID).

More reasons why the bulk web service is not included as part of the spec: If you have a URL, you can just resolve the URL and any sorts of redirects or whatnot can occur to get you to the record where you need to be, but a bulk query can have many URL maintenance issues.

Other futureproofing includes URLs potentially redirecting to other competencies entirely (I want to retire my competency and instead forward to X or Y competency) and more.

As for the relation type, there are not any indicators of "top level competencies". In the most general form, a framework is just a directed graph of competencies with the competencies as nodes and the relations as labeled edges (within or outside the framework). This flexibility allows us to represent ugly structures like [circles of (in)competence](http://www.axiametrics.com/wp-content/uploads/2011/06/circle.jpg).

Functions that perform operations like "get me the top level competencies in this framework" are candidates for the CASS library, though [I don't believe that specific one exists yet](cassproject/CASS#21).

If you are wondering why we are so flexible, it's partly due to our mission, which is to create a lowest common denominator between competency standards such that we can at least ingest all of the standards, and, presuming the standard allows it, export to any other competency standard.

**Comment by siuc-nate** [comment]
If the timestamp can be reliably stripped from the end of the `@id`, then it's probably fine.

As for the URLs, querying, etc., I agree that it is extremely flexible and probably the best way to store the data, since no piece of it is particularly reliant on any other piece. However, it does make for a lot of HTTP calls that retrieve small amounts of data. 

I would prefer to be able to send the ID of the framework (possibly with a parameter that indicates whether I want the competencies or the relations) to some endpoint and get back, as a list of objects, all of those things for that property for that framework. It would be roughly comparable to doing a search for competencies by `@id` for "id1 OR id2 OR id3 OR ...".

Alternatively, a parameter when retrieving the framework itself that will return all of the objects (rather than just their IDs) in its competencies/relations fields (is this what you mean by "bulk querying"? I'm not sure I follow what you were getting at, there).

Failing that, some endpoint that simply accepts a (large, probably via POST) list of IDs and returns all of the objects for them would at least avoid the overhead of sending 1000+ GET requests every time a user clicks on a framework to browse it. I think that alone would substantially speed things up.

**Comment by Lomilar** [comment]
SPDY and/or HTTP/2 are invaluable for 'lots of http calls'. Alas, HTTP/2 isn't quite stable enough for production (but oh boy is it fast). It is currently enabled on dev.cassproject.org. The repository is thread-safe, so it handles connections concurrently.

As for the 'bulk query', the last thing you mentioned is the undocumented API we have implemented. See image.
![image](https://user-images.githubusercontent.com/337692/27245332-aa66aa00-529f-11e7-8974-24a12ad88d97.png)

There's nothing wrong with some services that will go fetch all the records in a framework (no matter what server they are on) and return them, but we can't supply those as part of the core repository API.

I will list a bunch of reasons, but the overarching reason is: The repository runs based off of a permissioned CRUD API, which looks more like a distributed database API than an application API. Applications have hugely different use cases that, if we try to guess at, we're almost guaranteed to make much larger mistakes.

The ASN adapter is meant to be the beginning of an application API for serving the competency registry, and it will have a lot more ASN based assumptions in it, such as returning records in the same way that ASN does.

Here are the reasons.
 * If I write a framework with a thousand competencies that points at someone else's server for each of those, and I query for that framework a hundred times, I have just built a proxy multiplier (DDOS vulnerability).
 * It is difficult to state what should be fetched and what shouldn't be, it's also difficult to know what should have a @type, an @id, and how to refer to objects inside of other objects. JSON-LD has funny ways of allowing this, namely [data indexing](https://www.w3.org/TR/json-ld/#data-indexing). To avoid forcing people to check whether an object needs to be fetched (or, forbid, understanding advanced JSON-LD), we instead chose to just avoid inline objects unless absolutely necessary.
 * We also chose to avoid inline objects because they can be confusing. 
   * If you copy a framework, does it copy all the competencies? How split up is all this data?
   * Can I check signatures in objects that have been expanded? What if some internal object changes, does that invalidate the framework signature?
   * If I own the framework, do I own the competencies? (the answer is no) 
   * Is the server going to mess around with my data a lot, or if I put data in, can I get it out in the same fashion?

By keeping things very, very shallow (even at the cost of overhead), quite a bit is simplified.

**Comment by siuc-nate** [comment]
I can certainly see the potential benefits and reasoning for storing the data the way it's stored, from a maintenance/semantics/ownership/etc. standpoint, but it's also not very efficient to have to load every single relation, then pick through each of them just to find the relations for a single competency.  Even if it were done in SQL, hosted on the same box with no HTTP overhead, running 1000+ queries just to display one framework wouldn't be good design.  That kind of querying should happen within the data source itself, I think.

The multi GET endpoint is probably a step in that direction. It would be nice to not have to provide each individual ID, but since I am getting those back when I get the framework document itself anyway, that's probably not a problem. In our context, all of the relevant data will be stored within our CASS instance, so if the multi GET is something reliable (I assume it's undocumented for a reason), then I can build something based on it - but if not, then I need something more concrete.

**Comment by Lomilar** [comment]
I completely agree that the user shouldn't wait multiple minutes, which I can only imagine would be the case if one were using a single synchronous thread to query all the records.

If you're already trying to get the records concurrently, watch out for connection limits imposed by the environment. Chrome only allows 8 simultanous HTTP/1.1 queries to the same server, but unlimited HTTP/2 queries. System.Net.ServicePointManager.DefaultConnectionLimit appears to be limited to 2 per server.

Linked data and NoSQL style databases (like ElasticSearch) essentially require a high degree of concurrency and caching on the application layer to operate quickly and at scale, because of the lack of a (highly concurrent and cache-friendly) query language. This is a common problem with the web of data, since one record could come from Singapore, and the other from Norway.

This is where standards (and best practices) come in, such as mimicking how ASN is returned from the D2L server.

We can also create and implement trusted application specific APIs that fit your exact use cases and that plug into the CASS Repository. I'm game, just let me know what direction you want to go. :-)

**Comment by siuc-nate** [comment]
I don't know if it makes any difference on your end, but the way it's setup currently is that the client talks to the workit server, and that server then handles all of the requests to CASS.  It needs to do some preprocessing of the data before handing it back to the client anyway (specifically, it uses the relations to find the top level children and to inject the parent/child relationships into the competency nodes, so the javascript client-side only has one array of fleshed-out competency objects to deal with).

I suppose there are two general approaches, and @jkitchensSIUC might want to weigh in on this. Note that all of this assumes that the competency frameworks we deal with are ordinary hierarchies (so far, all the ones I've seen have been) rather than true graphs:

1. Browse frameworks one level at a time
   - More complex, but less up-front data load
   - Would need a way to get all top-level competencies for a framework
   - Would also need a way to find relations by competency ID, so that I could fetch the children of each competency node when needed as the user expands branches of the framework
      - This might be possible as-is with a search for the relation type and a field parameter of source or target where the value is the ID (I haven't tried it yet)
   - Still requires several requests per click (one to get the competency, one for each of its relations, and one for each target of those relations), but not so many that it should be noticeable
   - Requires 0-n recursive requests to get IDs for a subtree of competencies when the user decides to select/add that data to a credential

2. Display entire framework
   - Load entire framework up-front and display it client-side (for what it's worth, the O*NET framework in the dev sandbox comes out to something like ~800kb, comparable to an image file, so the raw amount of data should not be an issue)
   - Would need a way to get the entire framework (either preassembled or as lists of competency and relation objects rather than just the IDs - assembling them is easy once you have them, so the latter is fine) in as few calls as possible
      - Either 1 call to get a framework document with some parameter that causes it to include the competency/relation objects, or
      - 3 calls: One for the framework, one for the competencies, and one for the relations (It appears that this is possible with the existing multi GET endpoint)
   - Allows showing the whole framework, or collapsing it into browseable sections that require no additional requests when the user clicks to expand them
   - Allows client-side text searching of competencies within a framework
   - Makes it easier to add a subtree of competencies to a credential record, since all of the IDs will be present already

I rather strongly lean towards the second option, as it is much simpler.

**Comment by Lomilar** [comment]
(notes for me)
Remove the .txt extension and place this in Tomcat/etc/
[ce.js.txt](https://github.com/CredentialEngine/CompetencyFrameworks/files/1093144/ce.js.txt)

**Comment by Lomilar** [comment]
Much faster RS2 version. Keep old one for reference.
[ce.rs2.txt](https://github.com/CredentialEngine/CompetencyFrameworks/files/1093161/ce.rs2.txt)

**Comment by siuc-nate** [comment]
The search endpoint and the endpoint to load all competencies for a framework are working.  Do the notes above impact our implementation?  Or can this issue be closed?
