### ISSUE TITLE
Handling URIrefs to Frameworks with existing URIs ingested into CASS

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/CompetencyFrameworks#38]
I am wondering how CASS will handle an object property in one framework (e.g., a competency framework) that reference a node in a second famework (e.g., concept scheme). when both frameworks are mature in the sense that they have been assigned URI before ingestion into CASS. For example, we have coming the *beta Connecting Credentials* competency framework (ASN) and their complexity level vocabulary (SKOS). Both frameworks will come with Connecting Credentials URI already assigned. My understanding is that when ingested, entities in both frameworks are assigned CASS URIs and there is a reference for each pointing to the canonical versions of each in the Connecting Credentials namespace. 

My question is, what about object references within those vocabularies. For example, nodes in the competency framework reference nodes in the level concepts in the concept scheme, those references will come in with URI identifying nodes in the canonical Connecting Credentials namespace. **How will CASS handle this issue of inter-framework references in terms of their URI?**

![2017-08-02-uris_in_cass](https://user-images.githubusercontent.com/2939046/28887812-5e2f86ea-7773-11e7-8b2a-3aacce5579a9.png)

**Comment by Lomilar** [comment]
By default, we tend to expect people to create objects with identifiers that refer to those new objects by URL.

This rule is, I don't think, enforced. That is, an object in the repository can have an identifier that is external. Obviously, that URL will not result in the object that is stored in CASS, but there are ways to retrieve that object (search being the main one).

Let me test it real quick.

**Comment by Lomilar** [comment]
Ha! It does work.

So, objects can be copied and stored in the repository that "belong" elsewhere. They have a hidden identifier (that can be reused to re-retrieve the object), and the objects can be discovered.

I created a Schema.org/Thing, and assigned its ID to some bogus PERL URL.

I then posted the object to the CASS Repository using a made-up identifier (because the database has to store it somewhere).

https://dev.cassproject.org/api/custom/data/schema.org.Thing/EducationGrade1/100000

It can be found at that bogus identifier, or it can be discovered.

https://dev.cassproject.org/api/custom/data/?q=Thing

Or searched for more explicitly using a query string

https://dev.cassproject.org/api/custom/data/?q=@id:%22http://perl.org/EducationLevel/US/Grade/1%22

**Comment by Lomilar** [comment]
Frameworks and other objects can now be registered in CASS, and CASS will retain the canonical URLs. Because of the nature of these things, the object is discoverable via search, but the CASS url is separate.

We are currently using the following best practice:

The URL of a resource is constructed from the endpoint plus the md5 of the canonical ID in hex.

The canonical ID: http://connectingcredentials.org/competencies/c62c336f-a76d-4d7f-a777-367e7cc72d17
is findable at:
https://dev.cassproject.org/api/data/8eb2d64dff5b2a84c5da255d9d18de5b
or (in asn) at:
https://dev.cassproject.org/api/asn/8eb2d64dff5b2a84c5da255d9d18de5b

**Comment by Lomilar** [comment]
OK to close.

**Comment by Lomilar** [comment]
@stuartasutton @jkitchensSIUC @cwd-mparsons Reviving this discussion.

**Comment by stuartasutton** [comment]
Did any actionable conclusions from Wednesday's discussion?

**Comment by Lomilar** [comment]
Other than declaring terminology (import vs register), and discussing the nuances between them, I understood from Mike that the CER is capable of holding data with remote URIs, though I believe it still remains a policy discussion, surrounding what guarantees can be made for data that doesn't call the CER home.

**Comment by stuartasutton** [comment]
So, we need to handle the following:

1. Summarize pros/cons in terms of users of owners simply registering pre-existing competency frameworks and concept schemes "as is"--i.e., with their canonical URI's in place vs registry-uri'd copies; 
2. Summarize the trust issues (i.e., complete trust vs. simply lowering the uncertainty); and
3. Getting a definitive decision.

**Comment by stuartasutton** [comment]
Of course, my sense is that the probability is very high that some (many) resources will ultimately need or want to reference resources outside the CER...that's fundamental to Linked Data. So full trust is circumscribed by the boundary of the namespace.

**Comment by siuc-nate** [comment]
Is this covered by #61 ?

**Comment by stuartasutton** [comment]
It should be covered by #61.
