### ISSUE TITLE
Enable search paging

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#59]
In my opinion, the "Load 100...", "Load 1000...", and "Load All..." options are not intuitive or in line with how most (or any that I've seen) searches tend to work.  The search interface also resets to the beginning when you leave/return to it.

I think it would be more useful to enable:
1. Some form of paging (and/or "infinite scroll" - I prefer paging, but I know @jkitchensSIUC tends to prefer infinite scroll; is there a way to enable both?)
2. Returning to exactly where you left off in the search when you go back to it (this may render the paging/infinite scroll choice less relevant)

I'd like to see feedback from @stuartasutton and @jkitchensSIUC and @cwd-mparsons before suggesting that you actually take action on this issue, but it's something to consider.

**Comment by stuartasutton** [comment]
I was thinking about this very matter this morning because in working with the data (reviewing, editing etc.) I am bounding in and out from competency framework records to the TOC and find it maddening that I have to reselect how many I want to view each time. My earlier thoughts (which Nate's supersede) were: (1) default to all and let someone pick one of the fewer options; and (2)  once someone picks the number they want to see, retain that view number throughout a session as they move into records and back out the the TOC.

Nate's idea about remembering where in the TOC a person was as they entered and record so they can come back to the same place in the TOC when they return to it is an excellent idea as well.

**Comment by cwd-mparsons** [comment]
There is already a related issue for this on the Cass editor repo:
Means to retain last page of search results
https://github.com/cassproject/cass-editor/issues/237

**Comment by Lomilar** [comment]
https://github.com/cassproject/cass-editor/issues/371
