### ISSUE TITLE
Shortened/Canonical URI Plan

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/CompetencyFrameworks#8]
Short URLs that reference competencies are favored.

Ex: https://credentialEngineRegistry.org/competencies/<uuid\>

Describe the method that would retrieve resources from CASS using a Reverse Proxy, redirect, or some other method.

(Fritz Ed: This is supported, but requires some configuration)

This could also be done with concepts.

Ex: https://credentialEngineRegistry.org/concepts/<uuid\>

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton do we also need to document that PURL entries will need to be made?

**Comment by siuc-nate** [comment]
I don't believe so. The credentialengineregistry domain is meant to be the equivalent of a PURL (the "social commitment" Stuart talks about sometimes), so anything underneath it should be considered the same way (correct me if I'm wrong, @stuartasutton ).

**Comment by stuartasutton** [comment]
Correct.

**Comment by siuc-nate** [comment]
We also need to account for:
- Handling existing URIs (preferably using either sameAs or exactMatch, either within the body of the competency itself or as a type of relation)
- Whether or not rights management factors into this
- Potentially retrieving competencies by the existing URI rather than the CASS-generated URI

**Comment by siuc-nate** [comment]
addressed in #61
