### ISSUE TITLE
Competency ceasn:isPartOf is defined as multiple in spreadsheet, but is single when exported from CaSS

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CompetencyFrameworks#80]
In the CASS-ASN_Mappings mapping spreadsheet, ceasn:isPartOf is defined as multiple:
https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803

![image](https://user-images.githubusercontent.com/26332112/49677123-9a669600-fa42-11e8-9477-b09c612c237f.png)

However, data when exported from CaSS is single. 
![image](https://user-images.githubusercontent.com/26332112/49677207-22e53680-fa43-11e8-851a-43535e42d37a.png)

Same question for ceasn:isTopChildOf .

**Comment by Lomilar** [comment]
Huh, this seems new.

My previous understanding was that a competency can be part of one framework. Did this change recently?

**Comment by siuc-nate** [comment]
I think it's a question of "which way _should_ it be?"  I recall we've kind of gone back and forth on whether or not a competency can be in multiple frameworks @stuartasutton @Lomilar

**Comment by Lomilar** [comment]
Yes, we have.

Last I understood:

ASN presumes a competency will be part of one framework because conceptually, if a framework is changed, the context in which it was established (the framework) has also changed, and that having the same competency (the same @id) across mutliple frameworks can cause issues. This is embodied in the puzzles: "If I change a competency's parents, did I change the competency?", "If I change a competency's children, did I change the competency?", and "If I change a competency's context, did I change the competency?" -- All formulations at their essence of Theseus's paradox.

CaSS permits competencies to be included in multiple frameworks, because the notion of a framework in CaSS is not limited to being a conceptual framework, but it can also be a framework of application or computation, a crosswalk framework, and other types of frameworks that do not concern themselves with the above puzzles.

CTDL-ASN, last I knew, adhered to the ASN principles, and that's what we have been using to guide the UI/UX.

Outside data may not adhere to the ASN principles, which makes me expect that this issue will rise if a customer wishes to reuse URIs in multiple frameworks.

**Comment by stuartasutton** [comment]
Note that neither CTDL-ASN nor the ASN constrain whether a competency can exist in 1-n frameworks...that constrain is in the registry. With the exception of a flat framework (i.e., a straight enumeration of competencies), I stand my ground that context (structure) matters to meaning. That doesn't mean that a competency cannot be reused in 1-n frameworks and a derivative relationship noted.

**Comment by Lomilar** [comment]
Apologies, I must have missed that this constraint is specific to the registry. I note that I do believe that @stuartasutton's stance is completely valid and suitable business rules.

I believe the discussion still stands, even with my misconception.

Did the Registry's position on this change?

**Comment by siuc-nate** [comment]
If I remember right, we just need to know which way is correct so we can update our code accordingly.

**Comment by stuartasutton** [comment]
Currently, the editor is set to automatically generate an isPartOf relationship for all competencies in a framework. So, in essence, it functions  as not multiple. Until there is some verifiable reason for multiple, let's leave it at not multiple. Down the road, it can always be loosened to multiple without creating a namespace policy problem.

**Comment by Lomilar** [comment]
The need for multi value isPartOf and isTopChildOf may arise based on customer requirements, but it hasn't popped up yet.

**Comment by cwd-mparsons** [comment]
Closing as resolved - using a single value.
