### ISSUE TITLE
Use cass-viewer instead of cass-editor in view mode for Credential Finder?

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/CompetencyFrameworks#81]
@jkitchensSIUC @siuc-nate @cwd-mparsons 

Currently, the cass-editor in view mode is being used to show competencies:

![image](https://user-images.githubusercontent.com/337692/49902769-be96ee00-fe19-11e8-9b3b-2b2f334ea4d1.png)

If desired, we can begin customization of the cass-viewer towards the use case of displaying frameworks for the CE.

![image](https://user-images.githubusercontent.com/337692/49902807-ec7c3280-fe19-11e8-9cfc-5f4d0b95286b.png)

Is this something we should pursue? The cass-viewer is far more attractive and is intended to hide technical information.

**Comment by stuartasutton** [comment]
@Lomilar, @jkitchensSIUC, @siuc-nate, @cwd-mparsons,

A graphical interface to data ([and there are many to choose from](https://d3js.org/)) is always a plus when the user can get beyond the "wow" to useful traversal. Frequently, they don't scale up very well when they involve a large number of nodes, are highly structured (lots of traversal with high likelihood of getting lost), or don't have textual assertions that consistently begin with action verbs and otherwise meaningful text for graphical presentation.  

As a useful next step. let's see what a larger framework like the 162 node, hierarchically structured "Building Operator Certification (BOC) Level I Training Certificate of Completion Competencies" looks.

**Comment by Lomilar** [comment]
https://cass.credentialengine.org/ now has the cass-viewer.

The below image shows how to open a different framework under actions -> open. This button (and the align button) would be disabled in the CE use case where they are using CE tools to browse.

![image](https://user-images.githubusercontent.com/337692/49957666-60bbe200-febd-11e8-9531-25087b8f5ce9.png)

You can use the list view or the graph view to navigate. Click on the bubbles or use the tree on the left.

Also of note: this viewer is really a soft squishy feel-good for-the-general-public viewer, and is not meant  at all for technical use (URLs don't show up, no way to look at the data) so the cass-editor in view mode can still certainly be useful for a different audience, similar to how the JSON-LD links in the viewer are hidden in the bottom right corner.

**Comment by cwd-mparsons** [comment]
We are not currently using the viewer.
