### ISSUE TITLE
Frameworks in CASS not visible to admin users

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CompetencyFrameworks#92]
We have a case where multiple frameworks from Ivy Tech have been entered by that organization into CASS, but somehow this happened without the CE admin keys being attached. This means that while Ivy Tech can see those frameworks, the CE admin organization cannot.

Is it possible to add the admin keys after the fact, or to override the search if admin keys are selected to show all frameworks regardless?

**Comment by Lomilar** [comment]
Showing all frameworks regardless is achieved through eliminating &show=mine from the URL parameters of the cass-editor.

That it was imported without the CE admin keys being attached is strange, I am interested in finding the root cause of that. There is no 'permitted' way to attach the keys without acting on that organization's behalf -- and the controls that change ownership aren't included yet with the cass-editor, so it will have to be a script-based fix.

**Comment by Lomilar** [comment]
The @owner does exist. We need to, when show=mine is enabled, do a search using both the newline embedded public key and the non-newline-embedded public key to patch this issue (and reproduce this behavior for any type of owner/reader based search). Additionally, if owner or reader is being set in a template via a postmessage, we should try to parse a public key and then serialize it again so that it is transformed into the non-newline-embedded pubilc key.

This is less of a long term problem. We also need to revisit the indexing to ensure that elasticsearch indexing for @owner and @reader ignores newlines / whitespace.
